# Generated by Django 2.0.2 on 2018-03-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announce_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('announce_text', models.TextField()),
                ('submit_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('approve_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnounceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('admin_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=500)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_announce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Announcement')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirps.Announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_text', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TagSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_search_time', models.TimeField()),
                ('tag_search_date', models.DateField()),
                ('searched_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Tags')),
                ('user_searching_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.TimeField()),
                ('search_date', models.DateField()),
                ('searched_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='searched', to='chirps.Individual')),
                ('user_searching_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='searcher', to='chirps.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='submittag',
            name='submitted_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirps.Tags'),
        ),
        migrations.AddField(
            model_name='submittag',
            name='tag_submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual'),
        ),
        migrations.AddField(
            model_name='announcetags',
            name='the_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Tags'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='chirps.Individual'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitter', to='chirps.Individual'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirps.Organization'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chirps.Individual'),
        ),
        migrations.AlterUniqueTogether(
            name='usersearch',
            unique_together={('user_searching_user', 'searched_user')},
        ),
        migrations.AlterUniqueTogether(
            name='tagsearch',
            unique_together={('user_searching_tag', 'searched_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='submittag',
            unique_together={('tag_submitter', 'submitted_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='submitannouncement',
            unique_together={('submit_announce', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('saver', 'saved_announce')},
        ),
        migrations.AlterUniqueTogether(
            name='announcetags',
            unique_together={('the_announcement', 'the_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('org', 'user')},
        ),
    ]
