# Generated by Django 2.0.2 on 2018-04-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_text',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
