# Generated by Django 2.0.2 on 2018-04-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180402_1131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submitannouncement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submitannouncement',
            name='submit_announce',
        ),
        migrations.RemoveField(
            model_name='submitannouncement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='approver',
            field=models.ForeignKey(default='mark.penrod@gmail.com', on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='announcements.Individual'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='submitter',
            field=models.ForeignKey(default='mark.penrod@gmail.com', on_delete=django.db.models.deletion.PROTECT, related_name='submitter', to='announcements.Individual'),
        ),
        migrations.DeleteModel(
            name='SubmitAnnouncement',
        ),
    ]
