# Generated by Django 2.0.2 on 2018-04-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180421_2040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='org',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
