# Generated by Django 2.0.2 on 2018-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20180404_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='username',
        ),
    ]
